# Generated by Django 4.0.3 on 2022-03-06 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departements',
            new_name='Departments',
        ),
    ]
