# Generated by Django 4.0.3 on 2022-03-07 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_rename_departements_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='DepartementId',
            new_name='DepartmentId',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='DepartementName',
            new_name='DepartmentName',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='Departement',
            new_name='Department',
        ),
    ]
